name: flutter_hrm_inventory_pos_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  mat_month_picker_dialog: ^1.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menu/
    - assets/icons/
    - assets/icons/alert/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
